title: Himanshu Maheshwari
url: himanshuMaheshwari2311.github.io
author: Himanshu Maheshwari
email: m.himanshu2311@gmail.com
description: >
  Passionate software developer, curious about each and everthing about computure science. Open to learn anything interesting and collaborate on fun projects
show_excerpts: false # set to true to show excerpts on the homepage
paginate: 20
paginate_path: "/blog/page:num/"

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

# jekyll-dash date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
dash:
  date_format: "%d %b %Y"

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://www.linkedin.com/in/maheshwari-himanshu/
      icon: linkedin
      color: cyan
    - url: https://github.com/himanshuMaheshwari2311
      icon: github-square
      color: yellow
    - url: https://stackoverflow.com/users/5204691/stark?tab=profile
      icon: stack-overflow
      color: orange
    - url: https://twitter.com/tnf_stark
      icon: twitter
      color: blue
    - url: https://www.instagram.com/maheshwari_himanshu/
      icon: instagram
      color: red

# Build settings
remote_theme: bitbrain/jekyll-dash

plugins:
  - liquid-md5
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll/tagging

avatar_source: github
github_username: himanshuMaheshwari2311
